Project Transcendance {
  Note: '''
  # DBML for Transcendance
  DBML (database markup language) is a simple, readable DSL language designed to define database structures.

  ## Benefits

  * It is simple, flexible and highly human-readable
  * It is database agnostic, focusing on the essential database structure definition without worrying about the detailed syntaxes of each database
  * Comes with a free, simple database visualiser at [dbdiagram.io](http://dbdiagram.io)
  
  # how to use it

  ask Maieul :)
  '''
}

Table user {
  id integer [PK, not null, increment]
  name text [unique, not null]
  password text [null, Note: "If password is NULL, this means that the user is created through OAUTH2"]

  Note: "Represent a user"
}

Table auth {
  id integer [PK, not null, increment]
  provider text [not null]
  user integer [ref: > user.id, not null]
  oauth2_user text [not null, unique, Note: '''
    This makes sure that an oauth2 login is the always the same `user`
    Aka can't have two account bound to the same <OAUTH2> account
  ''']
}

Table session {
  id integer [PK, not null, increment]
  cookie text [PK, unique, not null]
  userid integer [ref: > user.id, not null]
  createAt text [not null]
  userAgent text [not null]
  reason integer [null]

  Note: "Every session for users"
}
