Project Transcendance {
  Note: '''
  # DBML for Transcendance
  DBML (database markup language) is a simple, readable DSL language designed to define database structures.

  ## Benefits

  * It is simple, flexible and highly human-readable
  * It is database agnostic, focusing on the essential database structure definition without worrying about the detailed syntaxes of each database
  * Comes with a free, simple database visualiser at [dbdiagram.io](http://dbdiagram.io)
  
  # how to use it

  ask Maieul :)
  '''
}

Table user {
  id text [PK, not null]
  login_name text [unique]
  display_name text [not null]
  password text [null, Note: "If password is NULL, this means that the user is created through OAUTH2"]
  otp text [null, Note: "If otp is NULL, then the user didn't configure 2FA"]
  guest integer [not null, default: 0]

  Note: "Represent a user"
}

Table auth {
  id integer [PK, not null, increment]
  provider text [not null]
  user text [ref: > user.id, not null]
  oauth2_user text [not null, unique, Note: '''
    This makes sure that an oauth2 login is the always the same `user`
    Aka can't have two account bound to the same <OAUTH2> account
  ''']
}
