CREATE TABLE IF NOT EXISTS user (
  id TEXT PRIMARY KEY NOT NULL,
  login_name TEXT UNIQUE,
  display_name TEXT NOT NULL,
  password TEXT,
  otp TEXT,
  guest INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS auth (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  provider TEXT NOT NULL,
  user TEXT NOT NULL,
  oauth2_user TEXT NOT NULL UNIQUE,
  FOREIGN KEY(user) REFERENCES user(id)
);
