Project Transcendance {
  Note: '''
  # DBML for Transcendance
  DBML (database markup language) is a simple, readable DSL language designed to define database structures.

  ## Benefits

  * It is simple, flexible and highly human-readable
  * It is database agnostic, focusing on the essential database structure definition without worrying about the detailed syntaxes of each database
  * Comes with a free, simple database visualiser at [dbdiagram.io](http://dbdiagram.io)
  
  # how to use it

  ask Maieul :)
  '''
}

Table user {
  id text [PK, not null]
  login text [unique]
  name text [not null, unique]
  password text [null, Note: "If password is NULL, this means that the user is created through OAUTH2 or guest login"]
  otp text [null, Note: "If otp is NULL, then the user didn't configure 2FA"]
  guest integer [not null, default: 0]
  oauth2 text [null, default: `NULL` , Note: "format: <provider>:<unique_id>; null if not logged via provider"]
  Note: "Represent a user"
}
