# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: maiboyer <maiboyer@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/06/16 14:57:11 by maiboyer          #+#    #+#              #
#    Updated: 2025/07/29 13:53:21 by maiboyer         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM trans_builder

# do extra stuff that is specific for this service here !

CMD ["node", "/src/icons/dist/run.js"]

